# Generated by Django 5.1.7 on 2025-04-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_game_status_alter_room_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='baseapp.room'),
        ),
    ]
