# Generated by Django 5.1.7 on 2025-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_game_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
