services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: maxjke114
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Измените порт
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/staticfiles
    environment:
      - DATABASE_URL=postgres://postgres:maxjke114@db:5432/postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxjke114
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web
volumes:
  postgres_data: